
---Alter table Add a "parent_id" column
alter table topics_category_masters
add column parent_id int
 
-- Insert sub_category of

--- Strategy Category
insert into topics_category_masters(name_en,name_he,is_active,"createdAt","updatedAt",parent_id) values('General','כללי',true,now(),now(),(select id from topics_category_masters where name_en='Strategy'));
insert into topics_category_masters(name_en,name_he,is_active,"createdAt","updatedAt",parent_id) values('Our product','המוצר שלנו ',true,now(),now(),(select id from topics_category_masters where name_en='Strategy'));
insert into topics_category_masters(name_en,name_he,is_active,"createdAt","updatedAt",parent_id) values('Our service','השירות שלנו',true,now(),now(),(select id from topics_category_masters where name_en='Strategy'));
insert into topics_category_masters(name_en,name_he,is_active,"createdAt","updatedAt",parent_id) values('Our efficiency','היעילות שלנו',true,now(),now(),(select id from topics_category_masters where name_en='Strategy'));
insert into topics_category_masters(name_en,name_he,is_active,"createdAt","updatedAt",parent_id) values('Our suppliers','הספקים שלנו',true,now(),now(),(select id from topics_category_masters where name_en='Strategy'));
insert into topics_category_masters(name_en,name_he,is_active,"createdAt","updatedAt",parent_id) values('Our clients','הלקוחות שלנו',true,now(),now(),(select id from topics_category_masters where name_en='Strategy'));

-- Management Category
insert into topics_category_masters(name_en,name_he,is_active,"createdAt","updatedAt",parent_id) values('General','כללי',true,now(),now(),(select id from topics_category_masters where name_en='Management'));
-- Engagement Category
insert into topics_category_masters(name_en,name_he,is_active,"createdAt","updatedAt",parent_id) values('General','כללי',true,now(),now(),(select id from topics_category_masters where name_en='Engagement'));
insert into topics_category_masters(name_en,name_he,is_active,"createdAt","updatedAt",parent_id) values('Our organizational culture','התרבות הארגונית',true,now(),now(),(select id from topics_category_masters where name_en='Engagement'));
insert into topics_category_masters(name_en,name_he,is_active,"createdAt","updatedAt",parent_id) values('Our employees','העובדים שלנו',true,now(),now(),(select id from topics_category_masters where name_en='Engagement'));
insert into topics_category_masters(name_en,name_he,is_active,"createdAt","updatedAt",parent_id) values('Our HR','מחלקת משאבי האנוש שלנו',true,now(),now(),(select id from topics_category_masters where name_en='Engagement'));

--topics_masters table insertion

alter table topics_masters add column check_type varchar

alter table topics_masters add column child_category_id int

-- Add new column "check_type"  Insert Value "CUSTOM"

-- General- Strategy Category-19
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'The frequency which we discuss our Vision','תדירות העיסוק בחזון שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'The frequency which we discuss our purpose','תדירות העיסוק בייעוד שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'The frequency which we discuss our strategy','תדירות העיסוק באסטרטגיה שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'Our understanding of our strategy','מידת ההבנה שלנו את האסטרטגיה של הארגון',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'The implementation of our strategy','יישום האסטרטגיה שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'Our business focus or focal points','המיקוד העסקי שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'Our client centric policy and its implementation','מדיניות המכוונות שלנו ללקוחות ויישומה',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'Our Suppliers as a key strategic issue','הספקים שלנו כנושא אסטרטגי משמעותי',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'The involvement of wide management levels in establishing the strategy','שילוב דרגי הנהלה רחבים בגיבוש האסטרטגיה',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'Defining key success factors for our strategy','הגדרת גורמי הצלחה מרכזיים לאסטרטגיה',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'Defining KPI’s for evaluating our strategy','הגדרת מדדי ביצוע מרכזיים להערכת האסטרטגיה שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'A recent business setback','כשל עסקי שקרה לאחרונה',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'A recent business success','הצלחה עסקית שאירעה לאחרונה',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'A recent organizational setback','כשל ארגוני שקרה לאחרונה',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'A recent organizational success','הצלחה ארגונית שאירעה  לאחרונה',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'Choose an image/metaphor reflecting our organization','בחר דימוי/מטאפורה לארגון שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'Choose an image/metaphor reflecting our vision','בחר דימוי/מטאפורה לחזון שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'Choose an image/metaphor reflecting our purpose','בחר דימוי/מטאפורה לייעוד שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'Choose an image/metaphor reflecting our strategy','בחר דימוי/מטאפורה לאסטרטגיה שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));


--Our Product Category Strategy -20
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our product' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'Fit of our product to clients needs','התאמת המוצר לצרכי הלקוח',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our product' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'My opinion regarding our product','עמדתי לגבי המוצר שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our product' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'Our products’ technology','הטכנולוגיה של המוצר שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our product' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'User interface of our product','ממשק המשתמש של המוצר שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our product' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'Client experience from our product','חוויית הלקוח מהמוצר שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our product' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'Our brand','המותג שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
--done
--Our service Category Strategy-21
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our service' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'Fit of our service to clients needs','התאמת השירות לצרכי הלקוח',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our service' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'My opinion regarding our service','עמדתי לגבי השירות שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our service' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'User interface of our service','ממשק המשתמש של השירות שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our service' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'Client experience from our service','חווית הלקוח מהשירות שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our service' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'Our brand','המותג שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
--Our efficency Category Strategy-22
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our efficiency' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'The way we utilize resources','אופן ניצול משאבים',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our efficiency' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'The way we manage the resource of time','ניהול זמן',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our efficiency' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'Redundancy and contingency in our organization','יתירות ותוכניות מגירה בארגון',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
--done
--Our suppliers Category Strategy-23

insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our suppliers' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'The value we create for our suppliers','הערך שאנו מייצרים לספקים שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our suppliers' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'The price we pay V the value we get from our suppliers','מחיר שאנו משלמים לספקים לעומת הערך שמקבלים',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our suppliers' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'The quality of service we receive from our suppliers','איכות השירות שאנו מקבלים מהספקים שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our suppliers' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'The quality of products we receive from our suppliers','איכות המוצרים שאנו מקבלים מהספקים שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our suppliers' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'The communication with our suppliers','התקשורת עם הספקים שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our suppliers' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'The relationship with our suppliers','מערכת היחסים עם הספקים שלנ',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));

--Our clients Category Strategy-24
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our clients' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'The value we create for our clients','הערך שאנו מייצרים ללקוחות שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our clients' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'The price we charge V the value we create for our clients','המחיר שאנו גובים לעומת הערך שאנו מייצרים ללקוחות שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our clients' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'The quality of service we provide our clients','איכות השירות שאנו מעניקים ללקוחות שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our clients' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'The quality of products we provide our clients','איכות המוצרים שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our clients' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'The communication with our clients','התקשורת עם הלקוחות שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our clients' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'The relationship with our clients','מערכת היחסים עם הלקוחות שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our clients' and parent_id=(select id from topics_category_masters where name_en='Strategy')),'Returning clients and clients loyalty','לקוחות חוזרים ונאמנות לקוחות',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Strategy'));

--General Category Management -25
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Management')),'Team work at our team','עבודת צוות בצוות הניהולי',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Management'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Management')),'The role of our team (what do we perform together as a team)','התפקיד שלנו כצוות (מה אנו עושים יחד כצוות)',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Management'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Management')),'Taking a role I want to take within the team','האם אני מצליח/ה לקחת את התפקיד שאני רוצה בצוות ההנהלה?',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Management'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Management')),'Trust amongst team members','אמון בצוות ההנהלה',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Management'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Management')),'Dialogue between team members','דו שיח בין חברי צוות ההנהלה',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Management'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Management')),'Leadership within the team','מנהיגות בצוות ההנהלה',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Management'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Management')),'Speaking up freely at our team','אפשר לדבר באופן חופשי בצוות',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Management'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Management')),'Accomplishing team missions','השגת מטרות ציוותיות',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Management'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Management')),'My engagement to the team','החיבור שלי לצוות',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Management'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Management')),'Relations with other teams','מערכות יחסים עם צוותים אחרים',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Management'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Management')),'Everything is thinkable and talkable in our team','ניתן לחשוב על הכל ולדבר על הכל בצוות שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Management'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Management')),'Do I have someone in my unit to consult regarding business challenges?','האם יש לי עם מי להתייעץ בצוות/יחידה על אתגרים עסקיים?',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Management'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Management')),'Do I have someone in the organization to consult regarding business challenges?','האם יש לי עם מי להתייעץ בארגון על אתגרים עסקיים?',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Management'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Management')),'Do I have someone in my unit to consult regarding communication and relationship challenges within the unit?','האם יש לי עם מי להתייעץ בצוות על אתגרי תקשורת ויחסים ביחידה שלי?',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Management'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Management')),'Do I have someone in the organization to resolve communication and relationship challenges within the organization ?','האם יש לי עם מי להתייעץ בארגון על אתגרי תקשורת ויחסים בארגון?',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Management'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Management')),'Is there a sufficient level of trust between managers and employees in my unit?','האם יש מידה מספקת של אמון בין מנהלים לעובדים ביחידה שלי?',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Management'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Management')),'Is there a sufficient level of trust between managers and employees in the organization?','האם יש מידה מספקת של אמון בין עובדים למנהלים בארגון?',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Management'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Management')),'Choose an event that occured in our team reflecting team work. Choose a color reflecting the event, then describe the event in detail.','בחר אירוע שקרה בצוות ומשקף עבודת צוות. בחר צבע המשקף את האירוע ותאר אותו בפירוט.',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Management'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Management')),'Choose an image/metaphor reflecting our team. Choose a color reflecting the image, then describe it in detail.','בחר דימוי/מטאפורה שמשקף את הצוות  שלנו. בחר צבע המשקף את הדימוי  ותאר אותו בפירוט.',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Management'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Management')),'Choose an image/metaphor reflecting our teamwork. Choose a color reflecting the image, then describe it in detail.','בחר דימוי/מטאפורה משקף את עבודת הצוות שלנו. בחר צבע המשקף את הדימוי ותאר אותו בפירוט.',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Management'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Management')),'Choose an image/metaphor reflecting the communication within our team. Choose a color reflecting the image, then describe it in detail.','בחר דימוי/מטאפורה שמשקף את התקשורת בצוות שלנו. בחר צבע המשקף את הדימוי ותאר אותו בפירוט.',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Management'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Management')),'Choose an image/metaphor reflecting the relationships within our team. Choose a color reflecting the image, then describe it in detail.','בחר דימוי/מטאפורה שמשקף את היחסים בצוות שלנו. בחר צבע המשקף את הדימוי ותאר אותו בפירוט.',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Management'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Management')),'Choose an image/metaphor reflecting our role as a team. Choose a color reflecting the event, then describe the event in detail.','בחר דימוי/מטאפורה שמשקף את עבודת הצוות שלנו. בחר צבע המשקף את הדימוי ותאר אותו בפירוט.',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Management'));

--Engagement Category General-26
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Engagement')),'I am ready to do anything for the success of our organization','אני מוכן/ה לעשות הכל להצלחת הארגון',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Engagement'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Engagement')),'My motivation when I wake up in the morning and go to work','המוטיבציה שלי כשאני קם בבקר ללכת לעבודה',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Engagement'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Engagement')),'My motivation in my role','המוטיבציה שלי בתפקיד',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Engagement'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Engagement')),'My engagement to my role','החיבור שלי לתפקידי',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Engagement'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Engagement')),'My connection to the organization','הקשר שלי לארגון',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Engagement'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Engagement')),'My engagement to the organization','החיבור שלי לארגון',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Engagement'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='General' and parent_id=(select id from topics_category_masters where name_en='Engagement')),'How do I feel regarding working and belonging to our organization?','איך אני מרגיש ביחס לעבודה ושייכות לארגון?',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Engagement'));

--Our organizational culture  Category-Engagement-27
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our organizational culture' and parent_id=(select id from topics_category_masters where name_en='Engagement')),'The way our managers communicate with us','הדרך בה המנהלים שלנו מתקשרים עימנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Engagement'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our organizational culture' and parent_id=(select id from topics_category_masters where name_en='Engagement')),'The way employees communicate with one another','הדרך בה עובדים מתקשרים בארגון',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Engagement'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our organizational culture' and parent_id=(select id from topics_category_masters where name_en='Engagement')),'How is our working environment?','איך סביבת העבודה שלנו?',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Engagement'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our organizational culture' and parent_id=(select id from topics_category_masters where name_en='Engagement')),'The general atmosphere within our organization','האווירה הכללית בארגון שלנו.',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Engagement'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our organizational culture' and parent_id=(select id from topics_category_masters where name_en='Engagement')),'The general atmosphere within our unit','האווירה הכללית ביחידה שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Engagement'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our organizational culture' and parent_id=(select id from topics_category_masters where name_en='Engagement')),'Is our work environment clean (no litter)?','האם סביבת העבודה שלנו נקייה (לא מלוכלכת)?',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Engagement'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our organizational culture' and parent_id=(select id from topics_category_masters where name_en='Engagement')),'Our environmental policies and thier implementation.','המדיניות הסביבתית שלנו ויישומה',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Engagement'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our organizational culture' and parent_id=(select id from topics_category_masters where name_en='Engagement')),'Innovation in our organization','חדשנות בארגון שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Engagement'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our organizational culture' and parent_id=(select id from topics_category_masters where name_en='Engagement')),'Creativity in our organization','יצירתיות בארגון שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Engagement'));

--Our employees Category-Engagement-28
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our employees' and parent_id=(select id from topics_category_masters where name_en='Engagement')),'The level of engagement of our employees','מידת החיבור של העובדים לארגון',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Engagement'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our employees' and parent_id=(select id from topics_category_masters where name_en='Engagement')),'The level of professionalism of our employees','מידת המקצועיות של העובדים שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Engagement'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our employees' and parent_id=(select id from topics_category_masters where name_en='Engagement')),'The level of innovation of our employees','מידת החדשנות של העובדים שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Engagement'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our employees' and parent_id=(select id from topics_category_masters where name_en='Engagement')),'The level of creativity of our employees','מידת היצירתיות של העובדים שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Engagement'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our employees' and parent_id=(select id from topics_category_masters where name_en='Engagement')),'The level of commitment of our employees','מידת המחויבות של העובדים שלנו',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Engagement'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our employees' and parent_id=(select id from topics_category_masters where name_en='Engagement')),'The way our employees behave at work','צורת ההתנהגות של העובדים שלנו בסביבת העבודה',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Engagement'));

--Our HR Category-Engagement-29
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our HR' and parent_id=(select id from topics_category_masters where name_en='Engagement')),'Do we have development and career plans for our managers and employees?','האם יש לנו תוכניות פיתוח קריירה לעובדים ומנהלים?',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Engagement'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our HR' and parent_id=(select id from topics_category_masters where name_en='Engagement')),'Do we have development and career plans for our managers?','האם יש לנו תוכניות פיתוח קריירה למנהלים?',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Engagement'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our HR' and parent_id=(select id from topics_category_masters where name_en='Engagement')),'Conflict resolution within the organization','אופן פתרון סכסוכים בארגון',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Engagement'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our HR' and parent_id=(select id from topics_category_masters where name_en='Engagement')),'Management development programs','תוכניות פיתוח מנהלים בארגון',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Engagement'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our HR' and parent_id=(select id from topics_category_masters where name_en='Engagement')),'Employees development programs','תוכניות פיתוח עובדים בארגון',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Engagement'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our HR' and parent_id=(select id from topics_category_masters where name_en='Engagement')),'Unit events and get togethers','פעילויות ומפגשים ברמת היחידות בארגון',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Engagement'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our HR' and parent_id=(select id from topics_category_masters where name_en='Engagement')),'Corporate events and get togethers','פעילויות ומפגשים ארגוניים',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Engagement'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our HR' and parent_id=(select id from topics_category_masters where name_en='Engagement')),'HR as a business partner','משאבי אנוש כשותף עסקי',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Engagement'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our HR' and parent_id=(select id from topics_category_masters where name_en='Engagement')),'HR as a mentor/internal consultant','משאבי אנוש כמנטור וכיועץ פנים ארגוני',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Engagement'));
insert into topics_masters(topic_category_id,name_en,name_he,is_active,"createdAt","updatedAt",check_type,child_category_id) values((select id from topics_category_masters where name_en='Our HR' and parent_id=(select id from topics_category_masters where name_en='Engagement')),'HR as a substantial player in the organization','משאבי אנוש כשחקן מרכזי בארגון',true,now(),now(),'CUSTOM',(select id from topics_category_masters where name_en='Engagement'));